### ISSUE TITLE
Option to disable auto config feature

### ISSUE THREAD

**Issue by BafS** [sindresorhus/atom-editorconfig#119]
Hi !
Firstly, thanks for this plugin, I use it each day !
Since a recent update you added an auto config feature, it's great but I don't need this on most project and it really slow down my computer ("Indexing...") with some big projects (thousand of files). Could it be possible to add an option to disable this feature ?

Thanks in advance !

**Comment by florianb** [comment]
Hi @BafS -- thank you for getting in touch!

I am sorry to hear you're facing issues with EditorConfig. I would be happy to fix that for you. I am unfortunately not sure what your problem is. What do you understand under the "auto config" feature?

Editorconfig is (or at least should) only doing file operations,

1. Once you open a new editor-pane with a file which isn't opened yet,
2. If you *save* an .editorconfig-file, all opened files will get their editorconfig reapplied.

This reapplying of settings should not significantly slow down your computer.

I would appreciate if you could describe a bit more detailed what you are experiencing and aht you expect instead. A list of your installed packages could also help since it is possible that there are any unseen cross-dependencies between the packages.

**Comment by BafS** [comment]
Hi, thanks for you reply !

In fact, I am not sure if it is editor config or not, sorry about that. I have the new "mouse" icon and "Indexing..." near it. I was thinking that editorconfig index files to guess the configuration but I am probably wrong. Sorry !

![screen shot 2016-10-27 at 17 59 57](https://cloud.githubusercontent.com/assets/588205/19774996/344c14fe-9c6f-11e6-8bbc-da9feaaf77b5.png)

**Comment by florianb** [comment]
You are welcome! Anyway thanks for clearing up this issue! 💝
