### ISSUE TITLE
`max_line_length` property

### ISSUE THREAD

**Issue by dmnd** [sindresorhus/atom-editorconfig#12]
The `max_line_length` property would be nice.

**Comment by jpolo** [comment]
+1

**Comment by cmbaer** [comment]
+1

**Comment by eriksape** [comment]
this would help? 

https://github.com/mustardamus/line-length-break

**Comment by florianb** [comment]
After thinking a little bit about its implementation i wonder how this should be implemented?

The editorconfig claims:

> [`max_line_length` f]orces hard line wrapping after the amount of characters specified

This means at any point in the editing process the editorconfig-plugin should insert a hard-wrap? I currently can't imagine that this might be any helpful, since it takes a additional operation (deleting the inserted newline) to fix a wrong wrap.
I don't know any file format which would tolerate any random hard-wraps.

The second question would be when should the break being introduced, at save of the document or on the fly, while editing the document?

Even though i currently don't see any practical use of a hard wrap over a soft wrap, and i'd expect this rule to be detected by a linter or being done by a "smart" plugin estimating the correct position of a hard wrap i expect to implement this in a few weeks, in order to fulfill the editorconfig-specs.

**Comment by Arcanemagus** [comment]
@florianb Isn't this the equivalent of setting:

```js
atom.config.set('editor.preferredLineLength', <max_line_length>)
atom.config.set('editor.softWrapAtPreferredLineLength', true)
```

At least according to [this page](https://github.com/editorconfig/editorconfig/wiki/Property-research:-maximum-line-length) a soft wrap at the set value is acceptable, it looks like the other page only lists a hard wrap as acceptable though, so it seems there is some confusion there.

Personally I would say the forced soft wrap is the more reasonable choice, for the difficulties and potentials to introduce confusion that you outline above for forcing an arbitrary line break at the set value.

**Comment by florianb** [comment]
@Arcanemagus - thank you very much, the link is very helpful. These config-settings seem to be the responsible settings (i had them in mind, too) - i have to check how they are implemented and how we may realize a per editor-config. 🍻

**Comment by PavelKonon** [comment]
max_line_length

**Comment by florianb** [comment]
🎺 The implementation of `max_line_length` is pending. I would appreciate any help testing it *before* we're releasing it: #123 (instructions can be found in the PR-description).

**Comment by florianb** [comment]
The current implementation of `max_line_length` is questioned by a raising number of users - i appreciate any contribution to #143.
