### ISSUE TITLE
insert_final_newline being removed and added again every save

### ISSUE THREAD

**Issue by scttcper** [sindresorhus/atom-editorconfig#121]
I'm back. When using `insert_final_newline = true` the final line at the bottom is being removed and added again every save. This blocks the undo button.

How to test:
1. Write some text on line 1
2. Manually add your own final newline
3. Write more text on line 1
4. Save
5. Undo (ctrl + z) should remove the text written in step 3 but instead it removes a newline that is being removed and written every save.

**Comment by florianb** [comment]
I hoped it would be you.. 😁 
Let me check that, but it is likely the undo-history is changed.

**Comment by florianb** [comment]
Okay.. i guess i have to apologize. The insert_final_newline-algorithm is badly implemented. I will fix that.

Would you either expect to have insert_final_newline create an undo-marker, if a final newline was added, or should it add the final newline silently? I guess i would prefer first, since every change should create an undo-marker, eh?

**Comment by scttcper** [comment]
I would expect a marker if it was added yeah

**Comment by florianb** [comment]
Aye.. expect a patch soon.

**Comment by florianb** [comment]
Hey @scttcper, the new patch is published. 🙏

**Comment by scttcper** [comment]
10/10 👍
