### ISSUE TITLE
Fallback to ~/.atom/.editorconfig

### ISSUE THREAD

**Issue by svoop** [sindresorhus/atom-editorconfig#159]
[Editorconfig](https://atom.io/packages/editorconfig) clashes e.g. with widely used [Whitespace](https://atom.io/packages/whitespace). However, disabling Whitespace is not really an option because you may use Atom in places where no `.editorconfig` is defined – most notably when using [remote-atom](https://atom.io/packages/remote-atom).

How about adding a fallback to `~/.atom/.editorconfig` if no `.editorconfig` is found down the current path? This way, Whitespace could be dropped in favour of Editorconfig everywhere.

**Comment by florianb** [comment]
Hi @svoop - thanks for your suggestion. You are absolutely right, currently this case is not properly handled by this package.

We won't support a "user"-based default `.editorconfig` because this is not part of the editorconfig-standard. Besides of that you're able to imitate such a behavior by putting a .editorconfig-file into a upper level-folder which is then recognized by the editorconfig-parser.

But to get back to your point, i would like to introduce a automated "deactivation" of packages in the fututure. But since this is a pretty intrusive procedure this is something which must be done pretty careful.

So unless this is solved in a satisfying way, we enabled a notification about potential misbehavior. I hope this explains why we are at the current state of functionality. ☕️

**Comment by svoop** [comment]
@florianb 

> But to get back to your point, i would like to introduce a automated "deactivation" of packages in the fututure. But since this is a pretty intrusive procedure this is something which must be done pretty careful.

Indeed, and with an opt-out fallback to the current behaviour maybe. I'd opt-in though :smile:

**Comment by florianb** [comment]
I am aware of your point. Sindre Sorhus advised me rightly to stick to a smart solution rathern than introducing configuration-options. Give me some more time to think about how this could be solved the smart way.

**Comment by Alhadis** [comment]
Currently, any EditorConfig setting that's `unset` will defer to the usual default configured in Atom's settings. This is a sane fallback with minimal surprises; if a user wishes to configure their preferred default, it can be done in `~/.atom/config.cson` instead of duplicating the preference between two config files (`~/.atom/config.cson` and `~/.atom/.editorconfig`).

As for the `whitespace` package... well, I'll work on bitch-slapping it into submission. 😉
