### ISSUE TITLE
linter-editorconfig?

### ISSUE THREAD

**Issue by danielbayley** [sindresorhus/atom-editorconfig#189]
I was just wondering if this package might be better as a [linter](https://atom.io/packages/linter) plugin? _linter-editorconfig_ maybe…

**Comment by florianb** [comment]
Hi @danielbayley - thanks for your suggestion. I know about the linter-environment. But i believe Atom-Editorconfig stays better a stand-alone package since it actively manipulates the editor's inner settings. Even though it is able to indicate some errors in your current files it is more about ensuring your editor is set up according to your `.editorconfig` settings.

This question also popped up in a different thread a while ago and the second reason why i won't implement a linter for editorconfig is the fact that most of the editorconfig-errors come in big bunch (f.e. all leading whitespaces are wrong formatted). Most of these errors also treat "invisible" aspects of the file - having a linter pointing these out gets pretty fast very annoying, i guess.

I hope this explains the reasoning why we aren't considering putting a linter-editorconfig up.
