### ISSUE TITLE
Apply settings for new files

### ISSUE THREAD

**Issue by brunetton** [sindresorhus/atom-editorconfig#21]

**Comment by caleb531** [comment]
For what it's worth, one can use the [advanced-new-file](https://atom.io/packages/advanced-new-file) package to create the file on disk just before Atom opens it, thus the `editorconfig` rules from wherever you saved the file will apply.

**Comment by florianb** [comment]
Thanks everybody for participating so far - after some further investigations i would like to either invalidate this issue or put it into a upcoming milestone. I beg for more patience. :coffee: :cake:

**Comment by florianb** [comment]
Sorry for getting back that late. After publishing 1.5.0 i must admit i don't think we could implement this feature in a functional style for two reasons:

- We need the file being saved to disk at the correct place (editorconfig-rules inherit) with the correct file extension (to make editorconfig choose the right rule) 
- We can't decide how to save the file and where

In my workflow i save the file as soon as possible to disk (or even start with a slight `touch`) to make Atom guessing the format right. I guess there are some people working like that in the Atom environment?

However, from 1.5.0 on atom-editorconfig recognizes you're opening a new (unsaved) file. It automagically searches and applies the .editorconfig as soon as you're saving the file.

I am closing this issue since there seems to be no legit alternative to that behavior. Hover feel free to come back or open a new issue if you feel i am wrong.

Thanks everybody! 🍻
