### ISSUE TITLE
How is max_line_length enforced / used?

### ISSUE THREAD

**Issue by aaronmagi** [sindresorhus/atom-editorconfig#210]
Hi,

I'm trying to understand how max_line_length is used within Atom using your plugin.  Typically in Eclipse if I have a maximum line length set I have to select the area and hit crtl + shift + f it will reformat the code to set the proper maximum line length.  How is this achieved in Atom using this package?

Thank you

editorconfig code:

`max_line_length = 160`

**Comment by florianb** [comment]
Hi @aaronmagi - we're setting Atom's setting "Preferred Line Length" according to the `max_line_length`. We leave it to Atom to "enforce" the line length. In fact it depends on Soft/Hard Wrap what happens - the soft wrap just breaks the line visually, the hard wrap adds a newline. In both cases the Wrap-Guide should be shown. But that feature might be broken since we need to follow up the latest API-changes.

**Comment by zwing99** [comment]
i think this is broken. it does not seem to be updating for me either

**Comment by awkaiser** [comment]
**Atom 1.23.3 + editorconfig 2.2.2:**

Indeed, guides display at `80` chars when _.editorconfig_ `max_line_length` is `120`

**Comment by thcolin** [comment]
Same with **Atom** `1.24.0` and **editorconfig** `2.2.2`

**Comment by manuelbieh** [comment]
Same with Atom `1.27.1` (and editorconfig `2.2.2`).

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
