### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-editorconfig#250]
Travis no longer provides free plan for OSS.

It should be based on https://github.com/chalk/chalk/blob/main/.github/workflows/main.yml, but made to work with Atom.

**Comment by the-j0k3r** [comment]
Plenty of examples e.g. https://github.com/bus-stop/x-terminal/tree/master/.github/workflows minimal adpation required obviously to suit this project

**Comment by Alhadis** [comment]
Atom's official sunset date is on December 15th, so between then and now, there's a slim chance of porting our tests to GitHub Actions… especially since Atom's package registry is [constantly unavailable](https://github.com/atom/atom/issues/25664) due to DDoS attacks from spam-bots publishing bullshit "packages". Which, in other words, means that the test-environment can't even be setup properly (since APM needs to make requests through Atom.io's APIs).

(FWIW, I already _did_ port the package's test-runner to GitHub Actions in [Atom-CI](https://github.com/Alhadis/Atom-CI)…)

**Comment by the-j0k3r** [comment]
@Alhadis for reference on our https://github.com/bus-stop/x-terminal project we have no such issues publishing/pushing updates, any of our releases continue to trigger updates within atom irrespective of any failures.
