### ISSUE TITLE
atom-editorconfig changes indentation after indentation-indicator reads it

### ISSUE THREAD

**Issue by bobrocke** [sindresorhus/atom-editorconfig#50]
This leads to indentation-indicator incorrectly displaying the actual indentation until I switch to another tab and back.

The indentation-indicator author suggests atom-editorconfig is not using the Atom API properly:

https://github.com/lee-dohm/indentation-indicator/issues/15#issuecomment-136217033

**Comment by sindresorhus** [comment]
> I'm not going to work around editorconfig's bug.

@lee-dohm And what might that bug be? Not a very useful assertion without any kind of evidence.

**Comment by lee-dohm** [comment]
@sindresorhus My apologies, my words were made in haste because I found @bobrocke's implication that I didn't want to do the right thing insulting, that somehow if I just realized how popular editorconfig is it might sway my decision to create a silly workaround when I had already said I would look into proper events that would fix the actual problem.

I still intend to see actual events created around changes to indentation settings that would not only fix this for interactions between editorconfig and indentation-indicator ... but all such interactions between indentation-interested packages.

**Comment by bobrocke** [comment]
But https://github.com/lee-dohm/indentation-indicator/issues/15#issuecomment-136217033 is marked as Won't Fix and Closed. Should it be re-opened if there's still a chance for a fix there?
